#Requires -RunAsAdministrator
<#
  Rescord Native Noise Suppression Installer
  - Downloads and silently installs Equalizer APO
  - Downloads werman/noise-suppression-for-voice VST plugin
  - Writes Equalizer APO config to enable the VST
#>

$ErrorActionPreference = "Stop"
$ProgressPreference    = "SilentlyContinue"   # speeds up Invoke-WebRequest

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Rescord Native Noise Suppression Setup   " -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# ─── Paths ───────────────────────────────────────────────────────────────────
$apoDir    = "C:\Program Files\EqualizerAPO"
$vstDir    = "$apoDir\VSTPlugins"
$configDir = "$apoDir\config"
$tmp       = $env:TEMP

# ─── Step 1: Equalizer APO ───────────────────────────────────────────────────
Write-Host "[1/4] Downloading Equalizer APO 1.4..." -ForegroundColor Yellow
$apoExe = "$tmp\EqualizerAPO64-1.4.exe"

try {
    Invoke-WebRequest `
        -Uri "https://sourceforge.net/projects/equalizerapo/files/1.4/EqualizerAPO64-1.4.exe/download" `
        -OutFile $apoExe `
        -UseBasicParsing
} catch {
    Write-Host "  Primary download failed, trying mirror..." -ForegroundColor DarkYellow
    Invoke-WebRequest `
        -Uri "https://downloads.sourceforge.net/project/equalizerapo/1.4/EqualizerAPO64-1.4.exe" `
        -OutFile $apoExe `
        -UseBasicParsing
}
Write-Host "  Downloaded." -ForegroundColor Green

Write-Host "[2/4] Installing Equalizer APO silently..." -ForegroundColor Yellow
$proc = Start-Process -FilePath $apoExe -ArgumentList "/S" -Wait -PassThru
if ($proc.ExitCode -ne 0 -and $proc.ExitCode -ne 3010) {
    # 3010 = success, reboot required — acceptable
    Write-Warning "  Installer exited with code $($proc.ExitCode). Continuing anyway."
}
if (-not (Test-Path $apoDir)) {
    Write-Error "Equalizer APO install directory not found at $apoDir. Install may have failed."
    Read-Host "Press Enter to close"
    exit 1
}
Write-Host "  Equalizer APO installed at $apoDir" -ForegroundColor Green

# ─── Step 2: werman VST Plugin ───────────────────────────────────────────────
Write-Host "[3/4] Downloading werman noise-suppression-for-voice..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $vstDir | Out-Null

$vstZip     = "$tmp\rnnoise-vst.zip"
$vstExtract = "$tmp\rnnoise-vst-extract"

# Try GitHub API for latest release, fall back to known v0.91
$assetUrl = $null
try {
    $rel = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/werman/noise-suppression-for-voice/releases/latest" `
        -Headers @{ 'User-Agent' = 'Rescord-Installer/1.0' }
    $asset = $rel.assets | Where-Object { $_.name -match 'win' -and $_.name -match '\.zip' } | Select-Object -First 1
    if (-not $asset) {
        $asset = $rel.assets | Where-Object { $_.name -match '\.zip' } | Select-Object -First 1
    }
    if ($asset) { $assetUrl = $asset.browser_download_url }
} catch {
    Write-Host "  GitHub API unavailable, using pinned release." -ForegroundColor DarkYellow
}

if (-not $assetUrl) {
    # Pinned fallback — werman v0.91 Windows VST2 x64
    $assetUrl = "https://github.com/werman/noise-suppression-for-voice/releases/download/v0.91/windows-rnnoise-bin.zip"
}

Write-Host "  Downloading from: $assetUrl" -ForegroundColor DarkGray
Invoke-WebRequest `
    -Uri $assetUrl `
    -OutFile $vstZip `
    -UseBasicParsing `
    -Headers @{ 'User-Agent' = 'Rescord-Installer/1.0' }

Write-Host "  Extracting..." -ForegroundColor DarkGray
Remove-Item -Recurse -Force $vstExtract -ErrorAction SilentlyContinue
Expand-Archive -Path $vstZip -DestinationPath $vstExtract -Force

# Find the VST2 DLL (prefer Stereo, then any .dll)
$dlls = Get-ChildItem -Recurse -Path $vstExtract -Filter "*.dll" |
        Where-Object { $_.Name -notmatch '(Mono|_x86)' } |
        Sort-Object { if ($_.Name -match 'Stereo') { 0 } else { 1 } }

if (-not $dlls) {
    Write-Error "No VST DLL found in the downloaded archive. Check $vstExtract manually."
    Read-Host "Press Enter to close"
    exit 1
}

$installedDll = $null
foreach ($dll in $dlls) {
    $dest = "$vstDir\$($dll.Name)"
    Copy-Item -Path $dll.FullName -Destination $dest -Force
    Write-Host "  Installed: $($dll.Name)" -ForegroundColor Green
    if (-not $installedDll) { $installedDll = $dest }
}

# ─── Step 3: Equalizer APO Config ────────────────────────────────────────────
Write-Host "[4/4] Writing Equalizer APO config..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $configDir | Out-Null

$configTxt = @"
# Rescord Native Noise Suppression
# Generated by Rescord — do not edit by hand
# To remove: delete this file or comment out the VST line.

Preamp: -6 dB
VST: $installedDll

"@

Set-Content -Path "$configDir\config.txt" -Value $configTxt -Encoding UTF8
Write-Host "  Config written to $configDir\config.txt" -ForegroundColor Green

# ─── Done ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  Installation Complete!                   " -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor White
Write-Host "  1. Restart your computer for Equalizer APO to take effect." -ForegroundColor Yellow
Write-Host "  2. After restart, Equalizer APO will be active system-wide." -ForegroundColor Yellow
Write-Host "  3. You can disable it anytime via the Equalizer APO GUI." -ForegroundColor Yellow
Write-Host ""
Write-Host "NOTE: Turn off 'AI Noise Suppression' in Rescord's Voice & Audio" -ForegroundColor DarkYellow
Write-Host "settings to avoid double-processing when native suppression is on." -ForegroundColor DarkYellow
Write-Host ""
Read-Host "Press Enter to close"
